server:
  port: 8081

spring:
  application:
    name: auth-service

user:
  service:
    url: http://localhost:8082  # URL of user-service

jwt:
  secret: mySecretKey
  expiration: 86400000   # 1 day in ms
